# Generated by Django 3.2 on 2022-05-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220520_1511'),
        ('actors', '0005_auto_20220520_1511'),
        ('accounts', '0002_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_actors',
            field=models.ManyToManyField(related_name='like_users', to='actors.Actor'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='like_users', to='movies.Genre'),
        ),
    ]
