# Generated by Django 3.2 on 2022-05-26 17:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_img/비로그인.png', null=True, upload_to='media'),
        ),
    ]
