# Generated by Django 3.2 on 2022-05-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='poster_path',
            new_name='profile_path',
        ),
    ]
