# Generated by Django 3.2 on 2022-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_remove_actor_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
