# Generated by Django 3.2 on 2022-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='movie2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='movie3',
            field=models.IntegerField(null=True),
        ),
    ]
