# Generated by Django 3.2 on 2022-05-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220518_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres_ids',
            new_name='genres',
        ),
    ]
