# Generated by Django 3.2 on 2022-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220517_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres_ids',
            field=models.ManyToManyField(related_name='movie', to='movies.Genre'),
        ),
    ]
