# Generated by Django 3.2 on 2022-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_genres_ids_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='movie', to='movies.Genre'),
        ),
    ]
