# Generated by Django 3.2 on 2022-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor3',
            field=models.IntegerField(null=True),
        ),
    ]
